version: '3'

services:
    dbapp:
        container_name: dbapp
        image: mysql:8
        restart: always
        volumes:
            - ./database:/var/lib/mysql
        env_file:
            - moodle_variables.env
        networks:
            - backendDB
        deploy:
            replicas: 1
            restart_policy:
                condition: any
    moodleapp:
        container_name: moodleapp
        #image: jhardison/moodle:latest
        build: .
        links:
            - dbapp:DB
        depends_on: 
            - dbapp
        restart: always
        volumes:
            - ./moodleapp-data:/var/moodledata
            - ./moodle:/var/www/html
        ports:
            - 2020:80
            - 443:443
        env_file:
            - moodle_variables.env
        networks:
            - backendDB
            - frontendWEB
        deploy:
            replicas: 1
            restart_policy:
                condition: any            

volumes: 
    db-volume:
    moodleapp-data:

networks:
    backendDB:
    frontendWEB: